version: '2.2'

volumes:
  database-volume: null
  elasticsearch-volume: null

services:

  setup:
    container_name: portal-setup
    build: ./setup/
    image: nmr/setup
    environment:
      - 'VIDISPINE_HOST=${VIDISPINE_HOST}'
      - 'VIDISPINE_TRANSCODER_URL=${VIDISPINE_TRANSCODER_URL}'
      - 'VIDISPINE_SOLR_PATH=${VIDISPINE_SOLR_PATH}'
      - 'VIDISPINE_THUMBNAIL_PATH=${VIDISPINE_THUMBNAIL_PATH}'
      - 'VIDISPINE_STORAGE_URI=${VIDISPINE_STORAGE_URI}'
      - 'ACTIVITI_USERNAME=${ACTIVITI_USERNAME}'
      - 'ACTIVITI_PASSWORD=${ACTIVITI_PASSWORD}'
      - 'ACTIVITI_DB_USER=${ACTIVITI_DB_USER}'
      - 'ACTIVITI_DB_PSWD=${ACTIVITI_DB_PSWD}'
      - 'ACTIVITI_HOST=${ACTIVITI_HOST}'
      - 'ACTIVITI_PORT=${ACTIVITI_PORT}'
      - 'POSTGRES_HOST=${POSTGRES_HOST}'
      - 'PORTAL_HOST=${PORTAL_HOST}'
    depends_on:
      - vidispineserver
      - activiti
    volumes:
      - './setup/quickstart:/quickstart'

  postgres:
    container_name: portal-postgres
    build: ./postgres/
    image: nmr/postgres
    restart: always
    environment:
      - 'POSTGRES_DB=${VIDISPINE_DB_NAME}'
      - 'POSTGRES_USER=${VIDISPINE_DB_USER}'
      - 'POSTGRES_PASSWORD=${VIDISPINE_DB_PSWD}'
      - 'PORTAL_DB_NAME=${PORTAL_DB_NAME}'
      - 'PORTAL_DB_USER=${PORTAL_DB_USER}'
      - 'PORTAL_DB_PSWD=${PORTAL_DB_PSWD}'
      - 'ACTIVITI_DB_NAME=${ACTIVITI_DB_NAME}'
      - 'ACTIVITI_DB_USER=${ACTIVITI_DB_USER}'
      - 'ACTIVITI_DB_PSWD=${ACTIVITI_DB_PSWD}'
    volumes:
      - 'database-volume:/var/lib/postgresql/data'

  vidispinetranscoder:
    container_name: portal-transcoder
    build:
      context: ./vidispinetranscoder/
      args:
        - VIDISPINE_VERSION=${VIDISPINE_VERSION}
    image: nmr/vidispinetranscoder
    restart: always
    ports:
      - '8888:8888'
    volumes:
      - './media/:/mnt/media'
    # logging:
    #   driver: "none"

  vidispinesolr:
    container_name: portal-solr
    build:
      context: ./vidispinesolr/
      args:
        - VIDISPINE_VERSION=${VIDISPINE_VERSION}
    image: nmr/vidispinesolr
    restart: always
    environment:
      - 'SOLR_HEAP=${SOLR_HEAP}'
    ports:
      - '8983:8983'
    logging:
      driver: "none"

  vidispineserver:
    container_name: portal-vidispine
    build:
      context: ./vidispineserver/
      args:
        - VIDISPINE_VERSION=${VIDISPINE_VERSION}
    image: nmr/vidispineserver
    restart: always
    environment:
      - 'VIDISPINE_DB_PSWD=${VIDISPINE_DB_PSWD}'
      - 'VIDISPINE_DB_USER=${VIDISPINE_DB_USER}'
      - 'VIDISPINE_DB_NAME=${VIDISPINE_DB_NAME}'
      - 'VIDISPINESERVER_HEAP=${VIDISPINESERVER_HEAP}'
      - 'POSTGRES_HOST=${POSTGRES_HOST}'
    ports:
      - '8080:8080'
      - '8088:8088'
      - '8089:8089'
      - '9001:9001'
    depends_on:
      - vidispinesolr
      - postgres
    volumes:
      - './media/:/mnt/media'
    # logging:
    #   driver: "none"

  elasticsearch:
    container_name: portal-elasticsearch
    build: ./elasticsearch/
    image: nmr/elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch-volume:/usr/share/elasticsearch/data'
    logging:
      driver: "none"

  kibana:
    container_name: portal-kibana
    build: ./kibana/
    image: nmr/kibana
    volumes:
      - './kibana/config/:/usr/share/kibana/config:ro'
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    logging:
      driver: "none"

  memcached:
    container_name: portal-memcache
    restart: always
    image: memcached

  rabbitmq:
    container_name: portal-rabbitmq
    image: rabbitmq
    restart: always
    environment:
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}'
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}'
      - 'RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}'
    logging:
      driver: "none"

  activiti:
    container_name: portal-activiti
    build: ./activiti/
    restart: always
    ports:
      - '8008:8080'
    depends_on:
      - postgres
    environment:
      - 'DB_TYPE=postgres'
      - 'DB_HOST=${POSTGRES_HOST}'
      - 'DB_PORT=${POSTGRES_PORT}'
      - 'DB_NAME=${ACTIVITI_DB_NAME}'
      - 'DB_USER=${ACTIVITI_DB_USER}'
      - 'DB_PASS=${ACTIVITI_DB_PSWD}'
    logging:
      driver: "none"

  portalbase:
    build:
      context: ./portal/
      args:
        - PORTAL_DOWNLOAD_URL=${PORTAL_DOWNLOAD_URL}
    image: nmr/portal
    environment:
      - 'VIDISPINE_USERNAME=${VIDISPINE_USERNAME}'
      - 'VIDISPINE_PASSWORD=${VIDISPINE_PASSWORD}'
      - 'VIDISPINE_HOST=${VIDISPINE_HOST}'
      - 'VIDISPINE_PORT=${VIDISPINE_PORT}'
      - 'DATABASE_USER=${PORTAL_DB_USER}'
      - 'DATABASE_HOST=${POSTGRES_HOST}'
      - 'DATABASE_NAME=${PORTAL_DB_NAME}'
      - 'DATABASE_PASSWORD=${PORTAL_DB_PSWD}'
      - 'MEMCACHED_HOST=${MEMCACHED_HOST}'
      - 'MEMCACHED_PORT=${MEMCACHED_PORT}'
      - 'DEBUG=${DEBUG}'
      - 'DEVELOPMENT_SYSTEM=${DEVELOPMENT_SYSTEM}'
      - 'RE3_LOCAL=${RE3_LOCAL}'
      - 'RABBITMQ_HOST=${RABBITMQ_HOST}'
      - 'RABBITMQ_PORT=${RABBITMQ_PORT}'
      - 'RABBITMQ_USER=${RABBITMQ_USER}'
      - 'RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}'
      - 'RABBITMQ_VHOST=${RABBITMQ_VHOST}'
      - 'ELASTICSEARCH_URL=${ELASTICSEARCH_URL}'
      - 'ELASTICSEARCH_USE_MORPHOLOGY=${ELASTICSEARCH_USE_MORPHOLOGY}'
      - 'NOTIFIER_HOST=${NOTIFIER_HOST}'
      - 'NOTIFIER_PORT=${NOTIFIER_PORT}'
      - 'PORTAL_CELERY_QUEUES=${PORTAL_CELERY_QUEUES}'
      - 'PORTAL_CELERY_NUM_WORKERS=${PORTAL_CELERY_NUM_WORKERS}'
      - 'ACTIVITI_HOST=${ACTIVITI_HOST}'
      - 'ACTIVITI_PORT=${ACTIVITI_PORT}'
      - 'ACTIVITI_USERNAME=${ACTIVITI_USERNAME}'
      - 'ACTIVITI_PASSWORD=${ACTIVITI_PASSWORD}'
      - 'PORTAL_HOST=${PORTAL_HOST}'
      - 'FLOWER_URL=${FLOWER_URL}'

  portal-web:
    container_name: portal-web
    extends:
      service: portalbase
    restart: always
    depends_on:
      - rabbitmq
      - postgres
      - elasticsearch
    privileged: true
    ports:
      - '80:80'
    environment:
      - PORTAL_ROLE=web

  celeryd:
    container_name: portal-celeryd
    extends:
      service: portalbase
    restart: always
    depends_on:
      - rabbitmq
      - postgres
      - elasticsearch
    privileged: true
    environment:
      - C_FORCE_ROOT=1
      - PORTAL_ROLE=celery
    logging:
      driver: "none"

  celerybeat:
    container_name: portal-celerybeat
    extends:
      service: portalbase
    restart: always
    depends_on:
      - rabbitmq
      - postgres
    privileged: true
    environment:
      - PORTAL_ROLE=beat
    logging:
      driver: "none"

  flower:
    container_name: portal-flower
    extends:
      service: portalbase
    ports:
      - '5555:5555'
    depends_on:
      - rabbitmq
    privileged: true
    environment:
      - PORTAL_ROLE=flower
    logging:
      driver: "none"

  notifier:
    container_name: portal-notifier
    extends:
      service: portalbase
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - rabbitmq
    privileged: true
    environment:
      - PORTAL_ROLE=notifier
    logging:
      driver: "none"
